ALTER TABLE SOLDIERS ADD rank VARCHAR(15);
ALTER TABLE SOLDIERS MODIFY (LASTNAME NULL);
ALTER TABLE SOLDIERS
MODIFY draftdate DATE DEFAULT TRUNC(SYSDATE);
ALTER TABLE SOLDIERS MODIFY releaseDate DATE DEFAULT TRUNC(ADD_MONTHS(SYSDATE, 36));
ALTER TABLE SOLDIERS
ADD FOREIGN KEY (c_ID) REFERENCES Crew(c_ID);


ALTER TABLE TANK
ADD FOREIGN KEY (c_ID) REFERENCES Crew(c_ID);

CREATE TABLE Crew
(
  c_ID NUMBER(9) NOT NULL,
  c_size NUMBER(9) NOT NULL,
  cID NUMBER(9) NOT NULL,
  PRIMARY KEY (c_ID),
  FOREIGN KEY (cID) REFERENCES COMMANDER(cID)
);

CREATE TABLE BASE
(
  base_ID NUMBER(9) NOT NULL,
  location VARCHAR(15) NOT NULL,
  PRIMARY KEY (base_ID)
);

ALTER TABLE TANK ADD  c_ID NUMBER(9)

CREATE TABLE SEA_VESSEL
(
  sea_ID NUMBER(9) NOT NULL,
  launcher_amount NUMBER(9) NOT NULL,
  nickname VARCHAR(15) NOT NULL,
  capacity NUMBER(9) NOT NULL,
  test_date DATE NOT NULL,
  lease_expiration_date DATE NOT NULL,
  c_ID NUMBER(9) NOT NULL,
  base_ID NUMBER(9) NOT NULL,
  PRIMARY KEY (sea_ID),
  FOREIGN KEY (c_ID) REFERENCES Crew(c_ID),
  FOREIGN KEY (base_ID) REFERENCES BASE(base_ID)
);

CREATE TABLE SUBMARINE
(
  oxygen_density FLOAT NOT NULL,
  max_depth NUMBER(9) NOT NULL,
  sea_ID NUMBER(9) NOT NULL,
  PRIMARY KEY (sea_ID),
  FOREIGN KEY (sea_ID) REFERENCES SEA_VESSEL(sea_ID)
);

CREATE TABLE WARSHIP
(
  cannons_amount NUMBER(9) NOT NULL,
  sea_ID NUMBER(9) NOT NULL,
  PRIMARY KEY (sea_ID),
  FOREIGN KEY (sea_ID) REFERENCES SEA_VESSEL(sea_ID)
);

CREATE TABLE MISSILE_SHIP
(
  missle_capacity NUMBER(9) NOT NULL,
  sea_ID NUMBER(9) NOT NULL,
  PRIMARY KEY (sea_ID),
  FOREIGN KEY (sea_ID) REFERENCES WARSHIP(sea_ID)
);

CREATE TABLE DESTROYER
(
  sea_ID NUMBER(9) NOT NULL,
  PRIMARY KEY (sea_ID),
  FOREIGN KEY (sea_ID) REFERENCES WARSHIP(sea_ID)
);
